### ISSUE TITLE
ImportError: cannot import name 'latexCmds'

### ISSUE THREAD

**Issue by Deathsbreed** [krassowski/Anki-Night-Mode#20]
Sorry, I'm not much of a Python guy so I don't know why this is failing or where to find this module, but I'm getting the error:

```
An error occurred in an add-on.

Please start Anki while holding down the shift key, and see if
the error goes away.

If the error goes away, please report the issue on the add-on
forum: https://anki.tenderapp.com/discussions/add-ons 

If the error occurs even with add-ons disabled, please
report the issue on our support site. 
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 47, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/nicolas/.local/share/Anki2/addons21/Night_Mode.py", line 50, in <module>
    from anki.latex import latexCmds
ImportError: cannot import name 'latexCmds'
```

My anki version is `Version 2.1.0beta6 Qt 5.9.1 PyQt 5.9` and I'm running it on ArchLinux directly from the repositories.

**Comment by krassowski** [comment]
Thank you for the message. I fixed it and tested against Anki 2.1 beta 6. The addon is still not usable on the newest beta but it is always a one problem less. Can you confirm that this error no longer appears?

**Comment by krassowski** [comment]
Newest version should work with 2.1 beta 6

**Comment by Deathsbreed** [comment]
Alright, I tested it and it seems to work. But it gives me an error upon startup (even though it's working), since it's a different error I'll probably open a different issue for it.

Thanks :)
